export const clerkAppearance = {
  variables: {
    colorPrimary: "#ff715b",
    colorText: "#f3eee5",
    colorTextSecondary: "#a8a5ad",
    colorBackground: "#111216",
    colorInputBackground: "#0b0c0f",
    colorInputText: "#f3eee5",
    colorNeutral: "#22242b",
    borderRadius: "0.875rem",
    fontFamily: "Arial, Helvetica, sans-serif",
  },
  elements: {
    rootBox: "resulens-clerk-root",
    card: "resulens-clerk-card",
    headerTitle: "resulens-clerk-title",
    headerSubtitle: "resulens-clerk-subtitle",
    socialButtonsBlockButton: "resulens-clerk-social-button",
    socialButtonsBlockButtonText: "resulens-clerk-social-button-text",
    dividerLine: "resulens-clerk-divider-line",
    dividerText: "resulens-clerk-divider-text",
    formFieldLabel: "resulens-clerk-label",
    formFieldInput: "resulens-clerk-input",
    formFieldAction: "resulens-clerk-action",
    formButtonPrimary: "resulens-clerk-primary-button",
    footerActionText: "resulens-clerk-footer-text",
    footerActionLink: "resulens-clerk-footer-link",
    formFieldErrorText: "resulens-clerk-error",
    alert: "resulens-clerk-alert",
    identityPreviewEditButton: "resulens-clerk-action",
    otpCodeFieldInput: "resulens-clerk-input",
  },
};
