export const clerkAppearance = {
  variables: {
    colorPrimary: "var(--foreground)",
    colorText: "var(--foreground)",
    colorTextSecondary: "var(--muted)",
    colorBackground: "var(--card)",
    colorInputBackground: "var(--input-background)",
    colorInputText: "var(--foreground)",
    colorNeutral: "var(--foreground)",
    borderRadius: "1.25rem",
    fontFamily:
      '"Inter Variable", Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  elements: {
    rootBox: "resulens-clerk-root",
    card: "resulens-clerk-card",
    headerTitle: "resulens-clerk-title",
    headerSubtitle: "resulens-clerk-subtitle",
    socialButtonsBlockButton: "resulens-clerk-social-button",
    socialButtonsBlockButtonText: "resulens-clerk-social-button-text",
    dividerLine: "resulens-clerk-divider-line",
    dividerText: "resulens-clerk-divider-text",
    formFieldLabel: "resulens-clerk-label",
    formFieldInput: "resulens-clerk-input",
    formFieldInputShowPasswordButton: "resulens-clerk-password-toggle",
    formFieldAction: "resulens-clerk-action",
    formButtonPrimary: "resulens-clerk-primary-button",
    footerActionText: "resulens-clerk-footer-text",
    footerActionLink: "resulens-clerk-footer-link",
    formFieldErrorText: "resulens-clerk-error",
    alert: "resulens-clerk-alert",
    identityPreviewEditButton: "resulens-clerk-action",
    otpCodeFieldInput: "resulens-clerk-input",
  },
};
